/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__TestClass
#define __PYX_HAVE__TestClass


#ifndef __PYX_HAVE_API__TestClass

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int addTest(int, int);
__PYX_EXTERN_C void testPrint(void);
__PYX_EXTERN_C PyObject *createTestObject(void);
__PYX_EXTERN_C void addData(PyObject *, int);
__PYX_EXTERN_C char *printCls(PyObject *);

#endif /* !__PYX_HAVE_API__TestClass */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initTestClass(void);
#else
PyMODINIT_FUNC PyInit_TestClass(void);
#endif

#endif /* !__PYX_HAVE__TestClass */
