/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__TrainGenSamples
#define __PYX_HAVE__TrainGenSamples


#ifndef __PYX_HAVE_API__TrainGenSamples

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *createSampleGenerator(void);
__PYX_EXTERN_C void sample(PyObject *, float *, float *);
__PYX_EXTERN_C void samplerTestPrint(void);
__PYX_EXTERN_C PyObject *createDummyObject(void);

#endif /* !__PYX_HAVE_API__TrainGenSamples */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initTrainGenSamples(void);
#else
PyMODINIT_FUNC PyInit_TrainGenSamples(void);
#endif

#endif /* !__PYX_HAVE__TrainGenSamples */
